= Linked Data Structures

== 문제. 리스트 문자열 만들기

* 리스트의 요소들을 나열한 문자열 생성을 위한 toString() 메서드 작성

**메서드**

* 형식
+
[source,java]
----
String toString(Node list)
----
* 반환 값
** 요소들이 포함된 문자열
* 참고
** 문자열 생성시 StringBuilder 사용

**보기**

* 코드
+
[source,java]
----
Node list = null;

System.out.println(toString(list));

list = new Node(1, new Node(2, new Node(3)));

System.out.println(toString(list));
----

* 결과
+
[source,console]
----
[]
[1, 2, 3]
----

== 문제. 리스트 요소 가져오기

* 리스트에서 i번째 요소를 반환하는 get() 메서드 작성

**메서드**

* 형식
+
[source,java]
----
int get(Node list, int i)
----
* 반환 값
** i번째 node의 요소
* 에러
** NoSuchElementException - 해당 요소가 없음

**보기**

* 코드
+
[source,java]
----
Node list = new Node(1, new Node(2, new Node(3)));

System.out.println(get(list, 1));
try {
    System.out.println(get(list, 4));
} catch(NoSuchElementException e) {
    System.out.println("Exception : NoSuchElementException");
}
----
* 결과
+
[source,console]
----
2
...
Exception : NoSuchElementException
----

== 문제. 리스트에 요소 추가하기

* 리스트의 새로운 요소를 추가하는 append() 메서드 작성

**메서드**

* 형식
+
[source,java]
----
Node append(Node list, int x)
----
** x를 리스트에 추가
* 반환 값
** 요소가 추가된 리스트

**보기**

* 코드
+
[source,java]
----
Node list = null;
System.out.println(toString(list));

list = append(list, 1);
System.out.println(toString(list));

list = append(list, 3);
System.out.println(toString(list));

list = append(list, 2);
System.out.println(toString(list));

list = append(list, 4);
System.out.println(toString(list));

----
* 결과
+
[source,console]
----
[]
[1]
[1, 3]
[1, 3, 2]
[1, 3, 2, 4]
----

== 문제. 리스트에 다른 리스트 추가하기

* 리스트에 다른 리스트의 요소들을 추가하는 append() 메소드 작성

**메서드**

* 형식
+
[source,java]
----
Node append(Node list1, Node list2)
----
* 반환 값
** list2의 요소가 추가된 list1

**보기**

* 코드
+
[source,java]
----
Node list1 = new Node(1, new Node(2, new Node(3)));
Node list2 = new Node(6, new Node(5, new Node(4)));

System.out.println(toString(list1));
System.out.println(toString(list2));

list1 = append(list1, list2);
System.out.println(toString(list1));
System.out.println(toString(list2));

----
* 결과
+
[source,console]
----
[1, 2, 3]
[6, 5, 4]
[1, 2, 3, 6, 5, 4]
[6, 5, 4]
----

== 문제. 리스트에 요소 삽입하기

* 리스트의 i번째에 새로운 요소를 삽입하는 insert() 메서드 작성

**메서드**

* 형식
+
[source,java]
----
Node insert(Node list, int i, int x)
----
** x를 i번째에 삽입
** i번째가 리스트의 마지막 다음이라면 추가한다.
* 반환 값
** 요소가 추가된 리스트
* 에러
** IndexOutOfBoundsException - 주어진 위치에 요소 삽입이 불가능한 경우

**보기**

* 코드
+
[source,java]
----
Node list = null;
System.out.println(toString(list));

list = insert(list, 0, 1);
System.out.println(toString(list));

list = insert(list, 1, 3);
System.out.println(toString(list));

list = insert(list, 1, 2);
System.out.println(toString(list));

list = insert(list, 3, 4);
System.out.println(toString(list));

try {
    list = insert(list, 10, 10);
    System.out.println(toString(list));
} catch(IndexOutOfBoundsException ignore) {
    System.out.println("Exception : IndexOutOfBoundsException");
}
----
* 결과
+
[source,console]
----
[]
[1]
[1, 3]
[1, 2, 3]
[1, 2, 3, 4]
Exception : IndexOutOfBoundsException
----

== 문제. 리스트의 길이 구하기

* 리스트의 길이를 구하기 위한 size() 메서드 작성

**메서드**

* 형식
+
[source,java]
----
int size(Node list)
----
* 반환 값
** 요소 수

**보기**

* 코드
+
[source,java]
----
Node list = null;
System.out.printf("size(%s) = %d%n", toString(list), size(list));
list = append(list, 1);
System.out.printf("size(%s) = %d%n", toString(list), size(list));
list = append(list, 2);
System.out.printf("size(%s) = %d%n", toString(list), size(list));
list = append(list, 3);
System.out.printf("size(%s) = %d%n", toString(list), size(list));
----
* 결과
+
[source,console]
----
size([]) = 0
size([1]) = 1
size([1, 2]) = 2
size([1, 2, 3]) = 3
----

== 문제. 리스트 요소의 합 구하기

* 정수 리스트의 값을 더해 반환하는 sum() 메서드 작성

**메서드**

* 형식
+
[source,java]
----
int sum(Node list)
----
* 반환 값
** 리스트 정수들 합

**보기**

* 코드
+
[source,java]
----
Node list = new Node(1);
System.out.println(sum(list));
list = append(list , 2);
System.out.println(sum(list));
list = append(list , 3);
System.out.println(sum(list));

try {
    list = null;
    System.out.println(sum(list));
} catch(NoSuchElementException ignore){
    System.out.println("Error : NoSuchElementException");
}
----
* 결과
+
[source,console]
----
1
3
6
Error : NoSuchElementException
----

== 문제. 리스트의 마지막 노드 삭제하기

* 리스트의 마지막 노드를 삭제하는 removeLast() 메서드 작성

**메서드**

* 형식
+
[source,java]
----
Node removeLast(Node list)
----
* 반환 값
** 마지막 노드가 삭제된 리스트

**보기**

* 코드
+
[source,java]
----
Node list = new Node(1, new Node(2, new Node(3)));

System.out.println(toString(list));
list = removeLast(list);
System.out.println(toString(list));
list = removeLast(list);
System.out.println(toString(list));
list = removeLast(list);
System.out.println(toString(list));

----
* 결과
+
[source,console]
----
[1, 2, 3]
[1, 2]
[1]
[]
----

== 문제. 리스트 복제 하기

* 리스트를 복제해 새로운 리스트를 생성하는 copy() 메서드 작성

**메서드**

* 형식
+
[source,java]
----
Node copy(Node list)
----
* 반환 값
** 동일한 요소로 복제된 새로운 리스트
* 참고
** 새 리스트는 반드시 원본 리스트와 완전히 독립적이어야 합니다.
** 한 리스트를 변경해도 다른 리스트에는 영향을 미치지 않아야 합니다.

**보기**

* 코드
+
[source,java]
----
Node list1 = new Node(1, new Node(2, new Node(3)));
Node list2 = null;

System.out.println(toString(list1) + " : " + toString(list2));
list2 = copy(list1);
System.out.println(toString(list1) + " : " + toString(list2));
list1=append(list1, 4);
System.out.println(toString(list1) + " : " + toString(list2));
----
* 결과
+
[source,console]
----
[1, 2, 3] : []
[1, 2, 3] : [1, 2, 3]
[1, 2, 3, 4] : [1, 2, 3]
----

== 문제. 리스트 부분 복제 하기

* 리스트의 지정 범위만 복제하는 copyOfRange() 메서드 작성

**메서드**

* 형식
+
[source,java]
----
Node copyOfRange(Node list, int p, int q)
----
* 반환 값
** 리스트에서 p번째부터 q번째 앞까지의 노드들을 복사한 새로운 리스트
* 참고
** 부분 복제된 새로운 리스트는 완전히 독립적이어야 합니다.
** 한 리스트를 변경해도 다른 리스트에는 영향을 미치지 않아야 합니다.

**보기**

* 코드
+
[source,java]
----
Node list1 = new Node(1, new Node(2, new Node(3)));
System.out.printlf(toString(list1));

Node list2 = copyOfRange(list1, 1, 3);
System.out.printlf(toString(list2));

----
* 결과
+
[source,console]
----
[1, 2, 3]
[2, 3]
----

== 문제. 리스트의 지정 요소 변경하기

* 리스트에서 i번째 요소를 변경하는 set() 메서드 작성

**메서드**

* 형식
+
[source,java]
----
void set(Node list, int i, int x)
----
** i번째 원소의 값을 x로 대체
** i번째 요소가 없을 경우, IndexOutOfBoundsException을 발생 시킴
* 반환 값
** 없음
* 에러
** NoSuchElementException - 지정한 위치에 요소가 없음

**보기**

* 코드
+
[source,java]
----
Node list = new Node(1, new Node(2, new Node(3)));
System.out.println(list);

set(list, 1, 4);
System.out.println(list);

try {

} catch(NoSuchElementException ignore) {
    System.out.println("Error : NoSuchElementException");
}
----
* 결과
+
[source,console]
----
[1, 2, 3]
[1, 4, 3]
Error : NoSuchElementException
----

== 문제. 리스트 요소 교환하기

* 리스트에서 주어진 i번째 요소와 j번째 요소를 교환하는 swap() 메서드 작성

**메서드**

* 형식
+
[source,java]
----
void swap(Node list, int i, int j)
----
** i번째 원소와 j번째 원소 교환
* 반환 값
** 없음

**보기**

* 코드
+
[source,java]
----
Node list = new Node(1, new Node(2, new Node(3)));
System.out.println(toString(list));

swap(list, 0, 2);
System.out.println(toString(list));

try {
swap(list, 1, 4);
} catch(NoSuchElementException ignore) {
    System.out.println("Error : NoSuchElementException")
}
----
* 결과
+
[source,console]
----
[1, 2, 3]
[3, 2, 1]
Error : NoSuchElementException
----

== 문제. 두개의 리스트를 정렬하여 합치기

* 2개의 리스트를 받아 정렬된 새로운 리스트를 생성하는 merged() 메서드 작성

**메서드**

* 형식
+
[source,java]
----
Node merged(Node list1, Node list2)
----
* 전제조건
** list1과 list2 모두 오름차순으로 정렬되어 있어야 함
* 반환 값
** list1과 list2의 모든 원소를 오름차순으로 포함한 새로운 리스트

**보기**

* 코드
+
[source,java]
----
Node list1 = new Node(1, new Node(2, new Node(5)));
Node list2 = new Node(1, new Node(3, new Node(4)));
System.out.println(toString(list1));
System.out.println(toString(list2));

Node list3 = merged(list1, list2);
System.out.println(toString(list3));
----
* 결과
+
[source,console]
----
[1, 2, 5]
[1, 3, 4]
[1, 1, 2, 3, 4, 5]
----

== 문제. 리스드의 요소를 왼쪽으로 이동시키기

* 리스트의 요소를 왼쪽으로 이동하는 rotateLeft() 메서드 작성
** 리스트의 첫 번째 원소를 마지막으로 이동

**메서드**

* 형식
+
[source,java]
----
Node rotateLeft(Node list)
----
* 반확 값
** 왼쪽으로 회전된 리스트
** 새로운 노드는 생성되지 않습니다.

**보기**

* 코드
+
[source,java]
----
Node list = new Node(1, new Node(2, new Node(3)));
System.out.println(toString(list));

list = rotateLeft(list);
System.out.println(toString(list));

list = rotateLeft(list);
System.out.println(toString(list));
----
* 결과
+
[source,console]
----
[1, 2, 3]
[2, 3, 1]
[3, 1, 2]
----

---

ifndef::github-env[]
endif::[]

ifdef::github-env[]
endif::[]
